### ISSUE TITLE
.NET Standard weaving

### ISSUE THREAD

**Issue by alexdrl** [keeper013/CrossCutterN#3]
Hello, we are interested in this project and we need to use it in a .NET Standard project... 

We ported SampleAdvice and Advice to the new csproj structure and netstandard1.4 and SampleTarget to .netcoreapp1.1.
When I try to weave the assembly, the weaving finishes correctly. but a mscorlib gets added to the final assembly. 

We are looking closely at this project, but we will need some features that PostSharp has like MSBuild task and some optimizations. For example CrossCutterN generates a try/catch even when the aspect does not define an action with the exception.

We cloud even try to contribute to the project if it fits our needs.

**Comment by keeper013** [comment]
Hi Alex:
Thanks for your time for this message.
Regarding your concerns about exception block, it's true that under some circumstances, exception block is generated even no advice for exception block is needed:
1. IReturn parameter must set HasReturn property to "false" to mark that there is no return value if exception is thrown
2. If later some advice for exit join point contains the "hasException" parameter, this value is set to false in exception block as well.
Since there is no other way I know of to find out if exception is thrown in finally block, that was the way to implement it. Please give me some hints if there is a better way to find out about exception thrown in finally block, and I'll do the optimization.

Regarding msbuild tasks, according to my understanding it's xml files driven by msbuild tool, or xbuild tool under mono. I'm not quite sure about how it is related to IL weaving process. If you are looking for a way to automate the execution of CrossCutterN.Command.exe in nightly build environment, would you try to open CrossCutterN.Test.csproj using notepad or notepad++? Find the target named "AfterBuild" and you can find the msbuild script to automate the IL weaving during build process defined inside that task. The script is already working in Travis CI automated integration which uses xbuild and mono. Not sure if it's what you are looking for.

Regarding the mscorelib issue, please forgive me for having no netcore related experiences in linux environment. I've no idea what the reason is, and as this project is totally not from my current job, I have too little time to set up the whole .NET standard project environment and try it out for now.

Regarding the contribution, considering the project was only online for half a month, it's quite a new born and the interfaces are not considered stable yet, I'd suggest to open a new branch or you can simply fork it to make the customization, it's under MIT license anyway. Whichever way you'd prefer, I'll try to do my best to help to develop this tool or provide suggestions. Would you think it's OK?

Please get back to me if more information is needed.

Thanks.

**Comment by alexdrl** [comment]
Hello, thank you for your detailed response.

We are trying to make CrossCutterN remove the mscrolib references that are added when weaving a .NET Standard DLL, if we make it work, we'll upload it to a fork of CrossCutterN, I'll send you an update about this.

About the MSBuild task, what I tried to explain is to pack CrossCutterN.Command functionality and the MSBuild execution into a CrossCutterN.Advice NuGet Package.

Sorry if I explained myself wrong, I did not want to push you in making this support .NET Standard assemblies, I was only trying to ask you if you knew about this.

Keep up the good work!!

**Comment by keeper013** [comment]
Hi Alex:

Just some thought regarding nuget packaging.
Actually CrossCutterN.Command depends on all assemblies in the solution except the to sample projects, and CrossCutterN.Advice is the basic supporting module that all other assemblies need, I would rather just call the package CrossCutterN if CrossCutterN.Command is included in the package.
The other thought is that which assemblies are to weave and what configuration to use is quite project specific. Currently I'm not sure how it can be generalized.

Thanks.

**Comment by keeper013** [comment]
Hi Alex:
The aspect switching feature needs current thread id for re-entrant read-write lock implementation. Which is only supported in .net standard 2.0. I guess I'll do the migration after its official release.
Thanks.
